name: ASAN, UBSAN, LSAN

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  gtest-with-msan:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get libc++ artifacts
      uses: actions/download-artifact@v4
      with: 
        name: libc++-with-msan-v1.0.0.deb
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: dvd0bvb/libcpp-with-msan

    - name: Install libc++ with msan
      run: ./install-libc++.sh ${{ secrets.GITHUB_TOKEN }}

    - name: Build gtest
      run: ./build-gtest.sh

    - name: Build deb package
      run: ./build-deb.sh
      