name: ASAN, UBSAN, LSAN

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  gtest-with-msan:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download and Install prebuilt libc++ with msan
      run: | 
        wget https://github.com/dvd0bvb/libcxx-with-msan/releases/download/v1.0.0/libc++-with-msan-v1.0.0.deb
        sudo dpkg -i libc++-with-msan-v1.0.0.deb

    - name: Build gtest package
      run: |
        ./build-gtest.sh
        ./build-deb.sh
      